package com.itechart.ny_accidents.entity

object AccidentsHeader {

  val date = "DATE"
  val time = "TIME"
  val latitude = "LATITUDE"
  val longitude = "LONGITUDE"

  val onStreet = "ON STREET NAME"
  val crossStreet = "CROSS STREET NAME"
  val offStreet = "OFF STREET NAME"
  val personsInjured = "NUMBER OF PERSONS INJURED"
  val personsKilled = "NUMBER OF PERSONS KILLED"
  val pedastriansInjured = "NUMBER OF PEDESTRIANS INJURED"
  val pedastriansKilled = "NUMBER OF PEDESTRIANS KILLED"
  val cyclistInjured = "NUMBER OF CYCLIST INJURED"
  val cyclistKilled = "NUMBER OF CYCLIST KILLED"
  val motoristInjured = "NUMBER OF MOTORIST INJURED"
  val motoristKilled = "NUMBER OF MOTORIST KILLED"
  val contributingFactors = Array("CONTRIBUTING FACTOR VEHICLE 1","CONTRIBUTING FACTOR VEHICLE 2","CONTRIBUTING FACTOR VEHICLE 3","CONTRIBUTING FACTOR VEHICLE 4","CONTRIBUTING FACTOR VEHICLE 5")
  val vehicleType =Array( "VEHICLE TYPE CODE 1","VEHICLE TYPE CODE 2","VEHICLE TYPE CODE 3","VEHICLE TYPE CODE 4","VEHICLE TYPE CODE 5")

  val DATE_C = 0
  val TIME_C = 1
  val LATITUDE_C = 4
  val LONGITUDE_C = 5
  val ON_STREET_NAME_C = 7
  val CROSS_STREET_NAME_C = 7
  val OFF_STREET_NAME_C = 9
  val PERSONS_INJURED_C = 10
  val PERSONS_KILLED_C = 11
  val PEDESTRIANS_INJURED = 12
  val PEDESTRIANS_KILLED = 13
  val CYCLIST_INJURED = 14
  val CYCLIST_KILLED = 15
  val MOTORIST_INJURED = 16
  val MOTORIST_KILLED = 17

  val CONTRIBUTING_FACTOR_VEHICLE_1_C = 18
  val CONTRIBUTING_FACTOR_VEHICLE_2_C = 19
  val CONTRIBUTING_FACTOR_VEHICLE_3_C = 20
  val CONTRIBUTING_FACTOR_VEHICLE_4_C = 21
  val CONTRIBUTING_FACTOR_VEHICLE_5_C = 22
  val CONTRIBUTING_FACTOR_VEHICLE_COLUMNS = Array(18, 19, 20, 21, 22)

  val VEHICLE_TYPE_CODE_1_C = 24
  val VEHICLE_TYPE_CODE_2_C = 25
  val VEHICLE_TYPE_CODE_3_C = 26
  val VEHICLE_TYPE_CODE_4_C = 27
  val VEHICLE_TYPE_CODE_5_C = 28
  val VEHICLE_TYPE_CODE_COLUMNS = Array(24, 25, 26, 27, 28)
}
